### ISSUE TITLE
Decide how we want to approach recording (A/V) and documentation of the event

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2020#21]
We'll need to develop and consider our plan for documentation in light of transitioning to an online format.

**Comment by dcwalk** [comment]
Here is link from Joly (NYC ISCO) on recent streaming from Hubs, shared on mailing list for AoIR: https://isoc.live/11917/

**Comment by Shrinks99** [comment]
So far the plan for this is to record and export all the BBB sources separately.  Recording to separate files for later playback is done by default with BBB but @ASoTNetworks and I have to figure out what the export process looks like for each session.  Only audio and video from people in BBB will be recorded and streamed.  Because all the source files are essentially the same, the post production workflow can be almost identical to last year!

Streaming content out of BBB is a system we still have to work out, MVP scenario is we just record the browser window but it would be much better to have the sources available in OBS.  This is another thing that we'll have to sort out once we get access to the meet.coop server.

**Comment by Shrinks99** [comment]
Update to this (same information that's included in my email and [meet.coop forum post](https://forum.meet.coop/t/our-networks-2020/289/4), you can skip this if you've already read either of those)

@ASoTNetworks and I have figured out a method of accessing the raw streams to get the individual presenter sources for post production!  This comes with some caveats and changes to our workflow.

**Caveat 1.** Rooms with recording enabled are always saving a cache to disk regardless of if a room currently shows as "recording" and we need to use that cache.  _Presenters need to be made aware that this is the case prior to their presentations._  Like previous years we will not be using any footage captured during the setup period in the final published videos and nobody but Elon and I will have access to it.

**Caveat 2.** We should use separate rooms per-presentation to ensure that we can end the call and move to the next presentation room.  Each presenter should be set up with their own room, when meetings are ended the cache files are saved to disk.

**Presentation Workflow**

- Presenter joins their room and turns on their video, microphone, and sets up screen sharing: They are now officially being recorded though none of the video will be used until we go live.
- I join the room with OBS and configure the browser sources to point to the presenter's sources
- We make sure their audio works and give them a countdown to going live
- They present, everyone thinks what they are talking about is neat
- We take questions from the chat via IRC which is passed along by a conference organizer present in the call
- The session ends and I transfer the stream to go to the in-between cards
- We end the BBB meeting, everyone gets kicked from the room, the recording ends and gets sent to the cache
- Elon pulls the specific meeting from the cache, names it the production code for that talk, and sends it to me over the Toronto Mesh cloud server

**Comment by dcwalk** [comment]
We did this! Thanks for the notes and we added a retro note to the repo. Closing
